// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iimqcrcghtehsnxetnfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpbXFjcmNnaHRlaHNueGV0bmZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MjgzODEsImV4cCI6MjA2MDUwNDM4MX0.Uc-JMoRi4Lf57us2j7epo6z_da_Wc4Fhc7ExDPUH1qY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);